llueve= True
es_feriado=False 
if llueve or es_feriado:
    print("me quedo en casa")
else:
    print("voy al SNPP")
    X=20
    if X>0: 
        print(f"{X}es mayor a cero")

x=17
if  x<20:
    print("x es mayor que 20")

valores=[1, 3, 4, 8]
if 5 in valores:
        print("está en valores")
        print("fin")

resultado=None
x=10
y=2
if y != 0:
      resultado = x/y
else:
      resultado=f"no se puede dividir {x} entre {y}"
      print(resultado)

x =28
if x<0:
      print(f"{x} es mayor que 0")
else:
      print("x es o")

x =28
if x>0:
      print(f"{x} es mayor que 0")
else:
      print("x es o")